---

 - name: update and upgrade host
   apt: 
     update_cache: yes
     upgrade: yes
   
 - name: install latest version Python and tools
   apt:
    name: ['python3-pip', 'python3-dev', 'build-essential', 'libssl-dev', 'libffi-dev', 'python3-venv']
    state: latest
